### PR TITLE
hover effect#370

### PR DESCRIPTION
**Pull request by GOURAVSINGH19**
I include a feature in search bar in which when user click on icon he/she automatically go to search bar and adjust the footer 

## Motivation and Context

Uploading Recording 2024-06-09 145528.mp4…

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GOURAVSINGH19** [comment]
Uploading Recording 2024-06-09 194921.mp4…

**Comment by sanket95droid** [comment]
@GOURAVSINGH19 please link the issue using Hash(#) followed by the issue number.
And also while making a PR make sure that the title indicated the issue that was solved.

**Comment by GOURAVSINGH19** [comment]
may it is done

**Comment by GOURAVSINGH19** [comment]
and one more thing I saw your github profile you have knowledge about three.js . actually  I am making on  my portfolio using r3f  in which in use my 3d model  but I face some problem so I need your help
If you have time for me  then I share my portfolio github with you..

**Comment by GOURAVSINGH19** [comment]
@sanket95droid

**Pull request merged**
