### PR TITLE
[Feature Request]: To See and Update Item Quantity on Cards #367

### PR DESCRIPTION
**Pull request by nishant0708**
[Feature Request]: To See and Update Item Quantity on Cards #367

## Description

Added feature to update item quantity in product card

## How Has This Been Tested?

-Add product and try to click all buttons

## Screenshots (if appropriate):
Screenshot 2024-06-10 013813

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [y ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [y ] My code follows the code style of this project.
- [y ] My change requires a change to the documentation.
- [y ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @sanket95droid can you please review this pr

**Comment by MAVRICK-1** [comment]
@nishant0708 there's a build problem going on with it , could change the name of all the class for product component
, or you can you tailWind css

**Comment by nishant0708** [comment]
Oo okay I will do it

**Comment by nishant0708** [comment]
hey @MAVRICK-1 Fixed it Changed all class name of product page name . You Can Check it Now

**Comment by nishant0708** [comment]
hey @MAVRICK-1 please review this pr

**Comment by sanket95droid** [comment]
@nishant0708 Please resolve the conflicts

**Comment by nishant0708** [comment]
hey @sanket95droid please check it now

**Pull request merged**
