### PR TITLE
Fix Hover effect in About Section

### PR DESCRIPTION
**Pull request by KomalSrivastava**
I have Fixed Hover effect in About Section as you scroll down there was an issue with hover that it was overflowing from the box. Fixed isssue number #490  

I have Fixed Hover effect in About Section as you scroll down there was an issue with hover that it was overflowing from the box. Now as you scroll down in about section close to footer area then you will see that the hover effect is filled in it .
## Screenshots (if appropriate):
image

@sanket95droid Kindly Review this and merge it.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@KomalSrivastava rebase it to dev branch

**Comment by KomalSrivastava** [comment]
@MAVRICK-1 Can you tell me how can i do it because when i am doing this lot of error is showing. just need little bit of help actually in vercel it is happening with  me. My most of the Pr is stuck because of this reason.

**Comment by MAVRICK-1** [comment]
@KomalSrivastava i solved the vercel issue now it's good to go , merge dev into your branch

**Comment by KomalSrivastava** [comment]
@MAVRICK-1 This showing lot of conflicts 
image
image
I have resolved all 25 in previous but not solved

**Comment by MAVRICK-1** [comment]
@KomalSrivastava do one thing create a new PR , I will mark it level 2.

**Comment by KomalSrivastava** [comment]
@MAVRICK-1 Okk

**Comment by KomalSrivastava** [comment]
@MAVRICK-1 can i take current branch as main?

**Comment by MAVRICK-1** [comment]
@KomalSrivastava u have to make a sub branch from dev

**Comment by KomalSrivastava** [comment]
@MAVRICK-1 Ok fine, i will make PR in morning.

**Pull request closed without merging**
