### PR TITLE
adding_mailto_tel_functionallity

### PR DESCRIPTION
**Pull request by AnitSarkar123**
solve issue #102 #77
you change the branch from main to the dev and i forked your main branch...sorry for this reason i don't understand why the merge conflicts is come sorry for late and please mearge it and review it

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 i will fix this and will merge this

**Comment by AnitSarkar123** [comment]
@MAVRICK-1 sir can you please assign me the issue no. #207

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 i will fix this and will merge this

Sir @MAVRICK-1 when you will merge it

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 my exams are going on , when i will get free time , i will do it

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 my exams are going on , when i will get free time , i will do it

Ok no problem sir @MAVRICK-1

**Comment by AnitSarkar123** [comment]
> > @AnitSarkar123 my exams are going on , when i will get free time , i will do it
> 
> Ok no problem sir @MAVRICK-1 

Sir @MAVRICK-1 can you marge it because today leaderboard will be release

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 i will to merge it by 8:00 pm , I got exam today

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 i will to merge it by 8:00 pm , I got exam today 

Ok,sir no problem also my exams are starts from June 1

**Comment by AnitSarkar123** [comment]
> > @AnitSarkar123 i will to merge it by 8:00 pm , I got exam today 
> 
> Ok,sir no problem also my exam is starts from June 1

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 error fixed done , mergin , congratulation for your first contribution

**Comment by AnitSarkar123** [comment]
> @AnitSarkar123 error fixed done , mergin , congratulation for your first contribution

Sir @MAVRICK-1 you give level 2 in issues but why level 1 in the PR

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 according to the new guidelines this doesn't fall under level2

**Comment by AnitSarkar123** [comment]
Sir @MAVRICK-1 can you send me the guidelines link because I don't know the guidelines even I don't know what is the meaning of level 1,lavel2, lavel3

**Comment by AnitSarkar123** [comment]
> Sir @MAVRICK-1 can you send me the guidelines link because I don't know the guidelines even I don't know what is the meaning of level 1,lavel2, lavel3..

**Comment by AnitSarkar123** [comment]
> Sir @MAVRICK-1 can you send me the guidelines link because I don't know the guidelines even I don't know what is the meaning of level 1,lavel2, lavel3

And what is the lavel of issue #207

**Pull request merged**
