### PR TITLE
Create Learn.md File for Project Guide  #16

### PR DESCRIPTION
**Pull request by Harshitazz**
## Description

This PR adds a new feature to the project where users can upload profile pictures to their accounts.

## Motivation and Context

This change is required to enhance user experience by allowing users to personalize their accounts with profile pictures. It solves the problem of accounts feeling impersonal and adds a visually appealing element to the user interface. This feature request was raised by several users in issue #123.

## How Has This Been Tested?

I tested this feature in both development and production environments. In the development environment, I used a local setup to ensure the feature functions as expected. In the production environment, I deployed the changes to our staging server and tested the feature with different user accounts to verify its functionality and compatibility with existing features.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@Harshitazz Congrats that a great work but there are some more things to add like branch name , if a contributor is creating a pull request it's branch name must be realted to a issue and contain issue number . Rest Everything ok after the changes it is ready to merge

**Review by MAVRICK-1 — COMMENTED** [review]
Congrats that a great work but there are some more things to add like branch name , if a contributor is creating a pull request it's branch name must be realted to a issue and contain issue number . Rest Everything ok after the changes it is ready to merge, Don't worry about the netlify checks

**Comment by Harshitazz** [comment]
is it good now?

**Comment by MAVRICK-1** [comment]
@Harshitazz include it in learn.md also .

**Comment by Harshitazz** [comment]
ig its done now

**Review by MAVRICK-1 — APPROVED** [review]

**Comment by MAVRICK-1** [comment]
@Harshitazz Thankyou

**Pull request merged**
