### PR TITLE
Nav hover and browse all category position Fixed

### LINKED ISSUE #247: Nav hover and browse all category position
**Describe the bug**
Remove the hover effect of navbar and fix the position of browse all category

### PR DESCRIPTION
**Pull request by Hemu21**
Nav hover and browse all category position Fixed

## Description

Remove the hover effect of navbar and fix the position of browse all category Fixed.

## Issue
[Issue Link](https://github.com/MAVRICK-1/e-commerce_website/issues/247) resolve #247 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hemu21** [comment]
@MAVRICK-1  When you get a free time please check and merge it.

**Comment by MAVRICK-1** [comment]
@Hemu21 remove the hover effect from navbar

**Comment by Hemu21** [comment]
@MAVRICK-1 done updated.

**Comment by MAVRICK-1** [comment]
@Hemu21 great work

**Pull request merged**
