### PR TITLE
added workflow as per issue #227

### LINKED ISSUE #227: Feat: Auto Commenting when an Issue is Closed
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to the problem of lack of communication and acknowledgment when issues are closed in the repository. Contributors may feel neglected or uncertain about the status of their issues if they are closed without any feedback or acknowledgment. This can lead to frustration and a decrease in motivation to contribute further.

**Describe the solution you'd like**
The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.

**Additional context**

issue closed

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #227 

## Description

The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@MAVRICK-1 please review and merge this PR

Also, please add labels to this PR

**Comment by Asymtode712** [comment]
@MAVRICK-1 why?

**Comment by MAVRICK-1** [comment]
@Asymtode712 After Looking into it deeply , I came to the conclusion that it is not needed.

**Comment by Asymtode712** [comment]
@MAVRICK-1 ok

**Pull request closed without merging**
