### PR TITLE
Updated Footer

### PR DESCRIPTION
**Pull request by kashhisshh**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@kashhisshh Screenshot 2024-05-11 102756
Changes are not reflected

**Comment by kashhisshh** [comment]
Lemme check again... Actually m new to git. And open contribution 
In my local it was showing properly..

**Comment by MAVRICK-1** [comment]
@kashhisshh it's working ,don't close it

**Comment by kashhisshh** [comment]
Sorry sir... Told you... m new to this just learning git...

**Pull request closed without merging**
