### PR TITLE
Profile Image Not Displaying Upon Sign-in Fixed

### LINKED ISSUE #24: Profile Image Not Displaying Upon Sign-in
## Issue Title
Profile Image Not Displaying Upon Sign-in

Screenshot 2024-05-09 223848

### Issue Description
Upon signing in, users are encountering an issue where their profile image fails to display correctly. Currently, the profile image is not showing up for users who sign in using their email and password. However, users signing in via Google authentication are able to see their Google profile image as expected.

### Expected Behavior
- When a user signs in using their email and password, their profile image should be displayed.
- When a user signs in using Google authentication, their Google profile image should be displayed.

### Steps to Reproduce
1. Navigate to the sign-in page.
2. Enter valid credentials (email and password) and sign in.
3. Observe that the profile image is not displayed.

### Proposed Solution
- For users signing in using email and password authentication, display a default [SVG image](https://icons8.com/icon/HmQQr0jYHZxu/male-user).
icons8-user

- For users signing in via Google authentication, retrieve and display their Google profile image.

### Priority
High

### Labels
bug, enhancement, authentication

### PR DESCRIPTION
**Pull request by Hemu21**
I made the profile image to dynamic. So that when user login they can see their profile image.

## Description

In the process of making the profile image dynamic. I had changed src/pages/SignIn/index.js, src/components/header/header.js and src/pages/SignIn/style.css

**Changes I made**

_src/pages/SignIn/index.js_

- In this file I take the user profile url when user login with google and saved that url.

_src/components/header/header.js_

- In this file take the default image from assest which is added by me which i had downloaded from the link given in issue.
- Then checked that we have the profile url or not. if we have profile url then display that else displayed the default image.

_src/pages/SignIn/style.css_

- Here I changed the loggin wrapper and login card height to auto. why because in mobile view it is showing some part of the signin. Now I had fixed it.

## Motivation and Context

When a user signs in using their email and password, their profile image should be displayed. When a user signs in using Google authentication, their Google profile image should be displayed. It will increase user experience.

## Issue

[Issue Like](https://github.com/MAVRICK-1/e-commerce_website/issues/24) resolve #24 

## How Has This Been Tested?

- set up in your localhost
- Try to login with email and google.
- If you login with email then you will find the default profile.
- If you login with google then you will find the gmail profile.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@Hemu21 
## the svg is not visible for email and password
Screenshot 2024-05-11 130444
## Make the a  logo  little smaller  and shift little bit towards the corner
Screenshot 2024-05-11 130915

after this changes it is ready to merge

**Comment by Hemu21** [comment]
@MAVRICK-1 Can you please check once. I had updated it now. I am able to see the profile login with email and password. Can you please check once.

**Comment by MAVRICK-1** [comment]
Screenshot 2024-05-11 163714




Still getting the same result , @Jiggy9 could you help him out with this issue

**Comment by Jiggy9** [comment]
@Hemu21 
image
 there's still problem with svg image, I suggest make it small and shift a bit bit to corner side, so it can fit it in proper size.
 Once you solve it send ss too with pull request

**Review by Jiggy9 — CHANGES_REQUESTED** [review]
there's 2 image with same name userProfile, but it conflicts with extension, either .gif or .png, use different names for both, to resolve this conflict.

**Comment by Hemu21** [comment]
@Jiggy9  it works fine without any problem in my localhost. but why it getting problem here, i doesn't understand. i tried material ui icons also.

**Comment by Jiggy9** [comment]
> @Jiggy9 it works fine without any problem in my localhost. but why it getting problem here, i doesn't understand. i tried material ui icons also.

I see, send ss of your output, additionally make sure it's visible for everytype of devices resoution, check layout constraints, and make it dynamic.

**Comment by Hemu21** [comment]
@Jiggy9  can you please see this 

desktop

responsive

google

**Comment by Hemu21** [comment]
@Jiggy9 First i used the gif provided in issue. I downloaded from the link. then admin said that using mail login icon is not show then i changed it to image, now i had changed it to mui material icon. till it is not showing. But it works fine in my localhost. what i have to do. can you please tell me

**Review by Jiggy9 — APPROVED** [review]

**Comment by Jiggy9** [comment]
> @Jiggy9 First i used the gif provided in issue. I downloaded from the link. then admin said that using mail login icon is not show then i changed it to image, now i had changed it to mui material icon. till it is not showing. But it works fine in my localhost. what i have to do. can you please tell me

@Hemu21 well I think it's working fine but there's conflict in index.js, fix it.

**Comment by Hemu21** [comment]
@Jiggy9 can you please check once. Till it getting same or updated?

**Comment by Jiggy9** [comment]
@MAVRICK-1 I think this problem is solved now, can u check once.

**Comment by MAVRICK-1** [comment]
@Jiggy9 does the user icon appearing ?

**Comment by MAVRICK-1** [comment]
Screenshot 2024-05-11 210115
it stiil doesn't working

**Comment by Jiggy9** [comment]
> Screenshot 2024-05-11 210115 it stiil doesn't working

@Hemu21 fix

**Pull request closed without merging**
