### PR TITLE
Improved Styling of "FAQ Section" Layout

### LINKED ISSUE #394: Feature 🌟: FAQ Section Layout Improvement
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1,
Here is the feature I want to suggest - 
The **Frequently Asked Questions** section of the website currently **lacks padding and margin**, resulting in a crowded appearance with no spacing between the FAQ items. 
Additionally, the section is not centered, which affects the overall visual appeal and user experience.

### Use Case

**Current Appearance:**
- No padding or margin around FAQ items.
- FAQ section aligned to full width of the page.

image

**Expected Appearance:**
- Adequate padding and margin around each FAQ item.
- FAQ section centered within the page for better aesthetics.

image

### Benefits

- Improved Readability
- Enhanced Visual Appeal
- Better User Experience
- Increased Engagement

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @MAVRICK-1, @sanket95droid 
issue closes #394 
## Description

The FAQ's section is modified to center it on the page, and made improvements to the styling to enhance readability and user experience. 
Additionally, i have **Added more FAQ questions** to the FAQ section to provide comprehensive information about the ONDC platform.

## Screenshots (if appropriate):
Here's how the page now looks like 

image

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.

Please take a look and review it.

### CODE REVIEW

**Comment by aslams2020** [comment]
@MAVRICK-1 @sanket95droid

**Comment by aslams2020** [comment]
@MAVRICK-1  @sanket95droid

**Comment by MAVRICK-1** [comment]
@aslams2020 will check this on Sunday

**Comment by aslams2020** [comment]
Okay! @MAVRICK-1 :)

**Review by dinxsh — APPROVED** [review]
looks good to me, good work!

**Comment by aslams2020** [comment]
@MAVRICK-1 , @sanket95droid and @dinxsh 

Please add the gssoc and level2 label (as assigned in the issue)

**Pull request merged**
