### PR TITLE
anchor tag styling fixed and link tags added into other items

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Description
anchor tag styling fixed and link tags added into other items

## Types of changes

- [✅ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ✅] My code follows the code style of this project.
- [ ✅] My change requires a change to the documentation.
- [✅ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@RamakrushnaBiswal can you  provide a screenshot in your PR

**Comment by RamakrushnaBiswal** [comment]
Screenshot_2024-05-12-18-04-33-47_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by MAVRICK-1** [comment]
@RamakrushnaBiswal i mean the changes you made in ui of the website

**Comment by RamakrushnaBiswal** [comment]
Sir in the top link tag is not working in compare, wishlist and cart button and also it's styling like if hover on it then the underline is showed but not now.

**Comment by MAVRICK-1** [comment]
> Sir in the top link tag is not working in compare, wishlist and cart button and also it's styling like if hover on it then the underline is showed but not now.

next time  plz mention the issue tag in PR , orelse it becomes  hard for the maintainers to understand.

**Pull request merged**
