### PR TITLE
[Feature Request]: Want to update Ui of Get in Touch page #412

### PR DESCRIPTION
**Pull request by nishant0708**
## Description
Updated UI Of Contact Card #412 

## Screenshots (if appropriate):
Screenshot 2024-06-29 024242

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ y] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [y ] My code follows the code style of this project.
- [y ] My change requires a change to the documentation.
- [y ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by dinxsh — APPROVED** [review]
looks good to me, good work

**Comment by nishant0708** [comment]
Hey @dinxsh can you add labels and assign it to me please

**Comment by dinxsh** [comment]
added @nishant0708

**Comment by nishant0708** [comment]
> added @nishant0708

Thanks can you do it for pr #429 as well please. It is not assigned

**Comment by dinxsh** [comment]
sure thing

**Pull request merged**
