### PR TITLE
[Feat]: GoToTop button added

### LINKED ISSUE #144: [Feat] :  Back to top Button
Problem:

The absence of a back-to-top button on the website significantly impairs its user-friendliness and navigational convenience, posing a notable problem in terms of user experience

Actual Behavior :

The Back to top button is not present

Expected Behavior : 

There should be a back to top button

Screenshot :
image

### PR DESCRIPTION
**Pull request by Arghyadeep09**
## Description

A "Back to Top" button has been implemented to enhance user experience by allowing users to effortlessly navigate to the top of the web page with a single click

## Motivation and Context

Long web pages can be challenging to navigate, especially on devices with smaller screens or limited scrolling capabilities. The "Back to Top" button provides users with a quick and convenient way to return to the top of the page without the need for extensive scrolling. This enhances the overall usability of the website and improves user satisfaction.

Issue link resolve #144 

## How Has This Been Tested?

go to the website scroll to the bottom you will notice a uparrow button on the bottom right of the webpage

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@Arghyadeep09 it looks fine re-solve merge conflict, then it will merge again

**Comment by Arghyadeep09** [comment]
Ok

**Comment by Arghyadeep09** [comment]
@MAVRICK-1 Resolved conflicts

**Comment by MAVRICK-1** [comment]
@Arghyadeep09 nice work, don't forget to give us a star

**Pull request merged**
