### PR TITLE
Fixes: Sign up & sign in form, Scrolltotop scaping, footer placement

### LINKED ISSUE #382: [Bug]: Fix widget spaces, Sign in page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Screenshot 2024-06-12 101312
Screenshot 2024-06-12 101334

### Expected behavior

Fix the form

increase space b/w

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sau-mili**
## Description

- Made the forms look visible, it was getting hidden
- Scroll to top button space added between chat widget and gototop widget
- space fixed between footer and newsletter

## Motivation and Context

for UI

fixes #382 
### NOW:
Screenshot 2024-06-12 222510
Screenshot 2024-06-12 222534
Screenshot 2024-06-12 230034
Screenshot 2024-06-12 230430

### BEFORE:
Screenshot 2024-06-12 101312
Screenshot 2024-06-12 101334

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sanket95droid** [comment]
@sau-mili Resolve the conflicts

**Comment by sau-mili** [comment]
done, please check

**Comment by sau-mili** [comment]
@MAVRICK-1 please check this

**Comment by MAVRICK-1** [comment]
Screenshot 2024-06-28 20020@sau-mili
@sau-mili

**Comment by sau-mili** [comment]
@MAVRICK-1 fixed it. please check

**Pull request merged**
