### PR TITLE
Solved the issue of page rendering at bottom

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #363 

## Screenshots (if appropriate):

https://github.com/MAVRICK-1/e-commerce_website/assets/154724111/bdfa9451-e49f-4aad-ba0f-3696e2971e06

- [x ] Bug fix (non-breaking change which fixes an issue)

- [x ] My code follows the code style of this project.

### CODE REVIEW

**Comment by pani2004** [comment]
@MAVRICK-1 Pls review the PR!!!

**Comment by pani2004** [comment]
@sanket95droid pls review the PR!!

**Comment by pani2004** [comment]
@sanket95droid pls merge the PR!!

**Comment by sanket95droid** [comment]
@pani2004 We are actually working on the deployment so we have some PRs in hold, dont worry we will merge your PR.

**Comment by pani2004** [comment]
ok @sanket95droid

**Comment by pani2004** [comment]
@sanket95droid pls merge this

**Comment by pani2004** [comment]
@MAVRICK-1

**Pull request merged**
