### PR TITLE
Feat/my account

### LINKED ISSUE #60: Adding the cart functionality and making dedicated My Account page
**Is your feature request related to a problem? Please describe.**
I would like to work on cart functionality as when user will add something in the cart it will get updated.

**Describe the solution you'd like**
For making the cart functionality  I have to make a "add to cart" button for all the products  and whenever user click the button the cart items value will be change and on clicking on the cart icon they will be able to see the selected items through a drawer or on a page. It will also show the total price for the selected items in the end. It will also have a "+" and "-" button to change the number of products they select.

**Describe alternatives you've considered**
@MAVRICK-1 
I am a GSSOC'24 contributor. please assign this to me so that I can work on this. I have worked on similar thing previously.

**Additional context**
I would also like to work on My account section by adding a dedicated page to see users account detail and users would be able to edit.

priority :  high

### PR DESCRIPTION
**Pull request by anwesha2002**
## Description

This PR adds feature of My Account .

## Motivation and Context
This will help to enhance the feature of the overall project
fixes #60 
(3 parts)

## How Has This Been Tested?

I have tested in my local machine and it is running well without any bugs
Screenshot 2024-05-14 132742

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@anwesha2002 CSS classes should be in hierarchical structure

**Comment by anwesha2002** [comment]
@MAVRICK-1 my prod build is absolutely fine  don't know what is the issue here.
Screenshot 2024-05-14 143911

**Comment by MAVRICK-1** [comment]
Screenshot 2024-05-15 08380@anwesha2002
@anwesha2002

**Comment by MAVRICK-1** [comment]
@anwesha2002 i resolved the merge conflicts, don't forget to give us a 🌟

**Comment by MAVRICK-1** [comment]
@anwesha2002 everything looks good only a minor change, make the image responsive

**Comment by MAVRICK-1** [comment]
@anwesha2002 it's good merging it now , will take care of responsiveness in another issue

**Pull request merged**
