### PR TITLE
[Feature Request]: About us Not able to scroll bug #447

### PR DESCRIPTION
**Pull request by nishant0708**
-fixed about us not able to scroll issue

[Feature Request]: About us Not able to scroll bug #447

## Screenshots (if appropriate):

https://github.com/MAVRICK-1/e-commerce_website/assets/101548649/5443373b-92d8-4020-ba7c-15970b388f59

## Types of changes

- [ y] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ y] My code follows the code style of this project.
- [y] My change requires a change to the documentation.
- [ y] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nishant0708** [comment]
hen @dinxsh can you review this pr

**Comment by dinxsh** [comment]
2 word pr? really? @nishant0708

**Comment by nishant0708** [comment]
> 2 word pr? really? @nishant0708

It just get solved in that only 😂 bro you could have merged it and not assigned any labels to it. Sorry for the trouble mam @dinxsh

**Comment by dinxsh** [comment]
closed since the about us scroll works for me. no worries though there are always other issues @nishant0708

**Comment by nishant0708** [comment]
hey @dinxsh see in about us there is a issue whenever the state of component changes it just scroll backs to top . See checkit 
go to about scroll down and hover on any card it will scroll you to top to fix that just in useeffect( ( ) ,  [ ] ) just add this array in useeffect it will be fine . its just bugging me so fix it from you end

**Comment by dinxsh** [comment]
oh, does it happen in localhost or live? it doesn't occur with me on the live link, if so you I can re-open and deploy this pull request

**Comment by nishant0708** [comment]
> oh, does it happen in localhost or live? it doesn't occur with me on the live link, if so you I can re-open and deploy this pull request

It is happening in local host

**Comment by dinxsh** [comment]
> > oh, does it happen in localhost or live? it doesn't occur with me on the live link, if so you I can re-open and deploy this pull request
> 
> It is happening in local host

do pull the new merged changes to fix then

**Pull request merged**
