### PR TITLE
Added pre-commit hooks

### PR DESCRIPTION
**Pull request by AvdhutPailwan**
pre-commit hooks added using husky and lint-staged is used which will run on every commit

## Description
- pre-commit hooks are added using husky
- lint-staged is used to lint staged files and with pre-commit hook lint-staged can lint all files before every commit
- pre-commit hooks will stop a user from committing a bad piece of code
- This closes the ticket #93 
- This closes the ticket #120 

## Motivation and Context

It can solve the problem of inconsistent code styling across all development platforms and the pre-commit can also be used to check if all test pass before every run

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@ratnesh-maurya please review this issue

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan their is merge conflict plz solve it , then it is ready to merge

**Comment by AvdhutPailwan** [comment]
@MAVRICK-1 I have resolved the merge conflict please check it.

**Comment by AvdhutPailwan** [comment]
I have resolved merge conflict please merge it

**Comment by AvdhutPailwan** [comment]
> I have resolved merge conflict please merge it

@MAVRICK-1

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan why so much commits? you can do it easy way by accepting both the changes.

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan Don't forget to give us a ⭐

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan Don't forget to give us a ⭐
> 

Yup 👍🏻

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan why so much commits? you can do it easy way by accepting both the changes.
> 

Actually I made changes but as new commits were getting merged new conflicts were arising that's why I made changes then reverted and deployment were failing as well so that's why so many commits happened 😅

**Pull request merged**
