### PR TITLE
Styling of the proceed to check out box Fixed

### LINKED ISSUE #108: Styling of the proceed to check out box
**Describe the bug**
The styling of the proceed to check out box is not well organisied.

**To Reproduce**

1. Go to cart or wishlist
2. check the procedd to check out box.

**Expected behavior**
proceed to check out box is well organized.

### PR DESCRIPTION
**Pull request by Hemu21**
Styling of the proceed to check out box Fixed

## Description

Styling of the proceed to check out box fixed. and made it responsive.

## Issue
[Issue Link](https://github.com/MAVRICK-1/e-commerce_website/issues/108) resolve #108 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@Hemu21 follow css hierarchy parent > child > grandchild ...

**Comment by MAVRICK-1** [comment]
and update your branch

**Comment by Hemu21** [comment]
@MAVRICK-1 I merged your changes it doesn't effect my changes can you please check it.

**Comment by MAVRICK-1** [comment]
@Hemu21 great work

**Pull request merged**
