### PR TITLE
Update footer.css

### LINKED ISSUE #419: Improve UI/UX of FAQ
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Improve UI/UX of FAQ. It looks simple and plain. Make it more visually appealing and making it advanced level

### Suggested Change

.

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by mahek0620**
Closes #419 

## Description

General Styling Enhancements:

Improved grid layout responsiveness in .footer-grid.
Adjusted padding, font sizes, and colors for better readability and visual appeal.
Enhanced hover effects (:hover) for interactive elements like boxes and links.

Footer Box Styling:

Enhanced styling of footer boxes (footerWrapper .footerBoxes .box) with consistent padding, background color, and border radius.

Typography and Color Adjustments:

Unified font sizes and colors across headings, links, and text elements (footer h3, footer .part1 h4, etc.).
Media Queries:
Added media queries for responsiveness across different screen sizes (@media (max-width: 1200px), @media (max-width: 992px), etc.).

Scroll Down Button:

Styled the scroll down button (scroll-down-btn) for better visibility and interaction.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mahek0620** [comment]
@

**Comment by mahek0620** [comment]
@dinxsh can you review it

**Review by dinxsh — APPROVED** [review]
LGTM

**Comment by mahek0620** [comment]
@dinxsh can you add labels to it

**Comment by dinxsh** [comment]
> @dinxsh can you add labels to it

added :)

**Comment by mahek0620** [comment]
@dinxsh in the issues you mentioned level2 but here you have given level1 please reupdate

**Comment by dinxsh** [comment]
updated

> @dinxsh in the issues you mentioned level2 but here you have given level1 please reupdate

**Pull request merged**
