### PR TITLE
Create Contact Us page

### LINKED ISSUE #270: [Feature Request]:  Contact Us page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create a Contact us page for the website .

### Use Case

It will help users to contact for any support .

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Description

I've created a contact us page for the website using email js .
closes : #270 

## Screenshots (if appropriate):

https://github.com/MAVRICK-1/e-commerce_website/assets/118350936/959a6c4b-8750-484f-bd74-afc7efc99cc1

https://github.com/MAVRICK-1/e-commerce_website/assets/118350936/df507d57-3f1a-4593-b047-9fd84f0dbb77

## Types of changes

our code introduce? Put an `x` in all the boxes that apply: -->

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
Hii @MAVRICK-1  I've created the page, and you can check it out. I've left the public key, service ID, and template ID as empty strings. You just need to enter your IDs, and then the code will start working completely.

**Comment by MAVRICK-1** [comment]
> Hii @MAVRICK-1 I've created the page, and you can check it out. I've left the public key, service ID, and template ID as empty strings. You just need to enter your IDs, and then the code will start working completely.

can you  tell me which service id ? or send me any documentation

**Comment by MAVRICK-1** [comment]
@Ayushmaanagarwal1211 and plz resolve the conflict , will merge it then

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure https://www.emailjs.com/  this is the website you have to just login to that and i am attaching a video below  you just need to go to email template where you can find service id .


https://github.com/MAVRICK-1/e-commerce_website/assets/118350936/48df0659-d31b-4230-a4e0-5011b125c216

Please see the video

**Pull request closed without merging**
