### PR TITLE
 overlapping of leaflet control button

### PR DESCRIPTION
**Pull request by BCA-444-9758-Ketan**
Issue no: #302

## Screenshots (if appropriate):

before fixing the issue⤵️
https://github.com/MAVRICK-1/e-commerce_website/assets/146806880/1204e247-99db-462e-b42d-cbe7ce6c8cbb

after fixing the issue⤵️
https://github.com/MAVRICK-1/e-commerce_website/assets/146806880/09aa6438-b684-4388-a648-30836992964a

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sanket95droid** [comment]
@Ketanop321 Please link the issue number

**Comment by BCA-444-9758-Ketan** [comment]
> @Ketanop321 Please link the issue number

#302

**Comment by sanket95droid** [comment]
@MAVRICK-1 Everything seems correct, though the changes have not been reflected in the dev branch deployed link.

**Comment by MAVRICK-1** [comment]
@sanket95droid yup you r right, will look into this afterwards, Thankyou for cross checking

**Pull request merged**
