### PR TITLE
Forgot password

### PR DESCRIPTION
**Pull request by Niharika0104**
Forget password implementation

## Description

I have added a page for forget password

## Motivation and Context

It will help users resolve the issue when they forgot the password

## How Has This Been Tested?

When users enter the password and if is not valid then validation error will be thrown
If email is valid then a message saying password link has been sent will be shown

## Screenshots (if appropriate):
forgetpassword

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@Niharika0104 every thing looks fine , there's a merge conflict plz solve it .

**Comment by Niharika0104** [comment]
Okay I will do that

**Comment by Niharika0104** [comment]
@MAVRICK-1 I resolved the conflicts

**Review by MAVRICK-1 — APPROVED** [review]

**Comment by MAVRICK-1** [comment]
@Niharika0104 thanx !!

**Comment by MAVRICK-1** [comment]
@Niharika0104 Don't forget to give us a ⭐

**Pull request merged**
