### PR TITLE
Added a Feedback Form/Page to the Website

### LINKED ISSUE #452: Feature✨ : Add a Feedback Form/Page to the Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1 , @dinxsh and @sanket95droid ,

I would like to add a feedback form/page to the website. 
Currently there is no Feedback form in the website, As 

To improve user experience and gather valuable insights from visitors, i suggest to add a feedback form/page to the website. This form will allow users to provide their opinions, report issues, and suggest improvements directly.

For example like this:

image

I will add Link to the Feedback Page in the Website's Footer.

### Use Case

Here's How will it work - 
- User Clicks on the "Give Feedback" button.
- System Displays the feedback form as a popup.
- User Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- Clicks the "Submit" button on the form.
- Displays a confirmation message indicating the feedback was submitted successfully.
- Closes the feedback form popup.

Could you please Assign me this issue ?

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @MAVRICK-1, @dinxsh and @sanket95droid
issue closes #452 

I have Added A Feedback Page and Form to the website. 

### Here's What I Did -
1. A dedicated page for **"Feedback"** matching the website design theme.
2. Feedback form of **input fields** for **name, email, and feedback.**
3. A **dynamic Rating system using emojis** (😡, 😒, 😐, 😊,😁) to **reflect user sentiment** rating 1,2,3,4,5 respectively.
4. Form submission functionality on **"Submit Feedback"** Button.
5. A **"Feedback Successfully submitted" popup** 
6. **Navigation link** in the Footer.

#### Here As you can see - 

https://github.com/MAVRICK-1/e-commerce_website/assets/131389695/42a347d5-a8c6-453c-a40d-d537bce071c6

please take a look and review it.
Thankyou! looking forward to contribute more..

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.

### CODE REVIEW

**Review by dinxsh — CHANGES_REQUESTED** [review]
good work, could you make it so the responses are sent to an email with some service like formspree, its a quick add-on!

**Comment by aslams2020** [comment]
> good work, could you make it so the responses are sent to an email with some service like formspree, its a quick add-on!

Sure @dinxsh , I will work on that.
Thanks for clarifying!

**Comment by aslams2020** [comment]
Hey @dinxsh, 
Will you provide me the following - 
1. Your FORM ENDPOINT url by Signing up on [Formspree](https://formspree.io/)

2. The email ID to which the email's should be sent.

Currently, this is the output with my emailid and url : 

image

(If there's anything more that i can modify in it..Please inform me)

**Comment by aslams2020** [comment]
Hey @dinxsh, 
Will you provide me the following - 
1. Your FORM ENDPOINT url by Signing up on [Formspree](https://formspree.io/)
2. The email ID to which the email's should be sent.

Currently, this is the output with my emailid and url : 

image

(If there's anything more that i can modify in it..Please inform me I learned and used formspree for the first time, Before this i used emailJs)
If approved..I will give full access to your emailid. thankyou!

**Comment by aslams2020** [comment]
@dinxsh , Should I raise a new issue to Implement this feature.
Also, Thankyou for Merging the PR!

**Comment by dinxsh** [comment]
it is alright, you can move ahead to other issues @aslams2020

**Comment by aslams2020** [comment]
oh ok, Got it!

**Comment by aslams2020** [comment]
@dinxsh please add the level and gssoc tag.

**Pull request merged**
