### PR TITLE
Fixed text colour in mobile view

### PR DESCRIPTION
**Pull request by dhairyagothi**
#436 
## Description
fixed text of navbar items colour 

before 
image

After 

image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@dinxsh please check and merge PR under GSSOC'24

**Review by dinxsh — CHANGES_REQUESTED** [review]
kindly make the parent text color white too here fashion to match the others looks

**Comment by dhairyagothi** [comment]
okay sure

**Comment by dhairyagothi** [comment]
image

@dinxsh check now

**Review by dinxsh — APPROVED** [review]
lgtm

**Pull request merged**
