### PR TITLE
Updated About Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #274 

image

I have added the features to the About Page with some hover animations and I have also made the page responsive.

@MAVRICK-1 please check and let me know if any changes are required. 

Also can you please assign this PR to me and add the gssoc and level labels?

Thankyou!

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Great work but make the css class hierarchical

**Comment by Hemashree21** [comment]
@MAVRICK-1 I have updated it sir

**Comment by MAVRICK-1** [comment]
@Hemashree21 great work don't forget to give a 🌟

**Comment by Hemashree21** [comment]
Thankyou! I have already starred the repo

**Pull request merged**
